- orthoseg/lib/predicter.py
Improve preformance by decoupling read operations in the prediction loop...
> Improve predict performance

- orthoseg/lib/predicter.py
- orthoseg/lib/trainer.py
- orthoseg/model/model_factory.py
- orthoseg/model/model_helper.py
- orthoseg/model/model_unet_ternaus.py
- orthoseg/train.py
Mainly tensorflow and/or keras import linting errors...
> Fix linting errors

- orthoseg/__init__.py
- orthoseg/load_sampleprojects.py
- orthoseg/util/config_util.py
- sample_projects/run_footballfields.py
- setup.py
- tests/test_end2end.py
- tests/test_train.py
> Feature add action load sampleprojects

- orthoseg/lib/predicter.py
- orthoseg/postprocess.py
- orthoseg/predict.py
- orthoseg/project_defaults.ini
> Add nb_parallel parameter to predict

- orthoseg/lib/postprocess_predictions.py
- orthoseg/util/vector_util.py
> Apply pre-simplify with RDP before applying LANG

- CHANGELOG.md
- orthoseg/lib/postprocess_predictions.py
- orthoseg/lib/predicter.py
- orthoseg/predict.py
- orthoseg/project_defaults.ini
> New: prediction parameter reclassify_to_neighbour_query

- ci/envs/38-latest-conda-forge.yaml
- ci/envs/39-latest-conda-forge.yaml
- orthoseg/lib/prepare_traindatasets.py
- tests/test_helper.py
- tests/test_postprocess_predictions.py
- tests/test_prepare_traindata.py
- tests/test_train.py
> Improve CI config

- CHANGELOG.md
- orthoseg/lib/prepare_traindatasets.py
- orthoseg/util/vector_util.py
- tests/test_helper.py
- tests/test_prepare_traindata.py
> Add check if location BBOXs are of the right size

- CHANGELOG.md
- orthoseg/lib/trainer.py
- orthoseg/model/model_factory.py
- orthoseg/model/model_helper.py
- orthoseg/project_defaults.ini
> Improve/add options to monitor training progress #49

- orthoseg/train.py
The hyperparam id's need to be the same... otherwise errors can occur.
> Run predict on training dataset only if similar neural network available

- CHANGELOG.md
- orthoseg/lib/prepare_traindatasets.py
- tests/test_prepare_traindata.py
> Add support for training data from layers in different projections

- CHANGELOG.md
- orthoseg/lib/prepare_traindatasets.py
- orthoseg/load_sampleprojects.py
- orthoseg/util/gdrive_util.py
- orthoseg/util/git_downloader.py
> Add option to disable ssl verify in load sampleprojects

- CHANGELOG.md
- orthoseg/util/ows_util.py
- tests/test_ows_util.py
> Automatically detect the axes order of the CRS used

- CHANGELOG.md
- orthoseg/predict.py
> Fix error in prediction on ubuntu 22.04

- orthoseg/predict.py
references #73 
No access to a linux development env anymore at the moment, so just disable for now
> Disable tensorrt optimization on linux

- orthoseg/helpers/config_helper.py
- orthoseg/util/ows_util.py
> Add support for WMS username + password

- orthoseg/lib/predicter.py
- orthoseg/lib/prepare_traindatasets.py
- orthoseg/load_images.py
- orthoseg/util/ows_util.py
- orthoseg/util/progress_util.py
- tests/test_end2end.py
- simplify code
- improve performance, especially if roi consists of several polygons located far apart
- move, rename and use ProgressLogger utility
> Refactor ows_util.get_images_for_grid

- sample_projects/imagelayers.ini
> Add example of wms_username and wms_password to sample imagelayers.ini

- CHANGELOG.md
- orthoseg/helpers/config_helper.py
- orthoseg/load_images.py
- orthoseg/postprocess.py
- orthoseg/predict.py
- orthoseg/train.py
- orthoseg/util/config_util.py
- tests/test_config.py
- tests/test_helper.py
> ENH: Add support to overrule configuration parameters via command line arguments

- .pre-commit-config.yaml
- environment-dev.yml
- orthoseg/lib/predicter.py
- pyproject.toml
Use ruff-format instead of black for formatting.
> MAINT: Use ruff-format instead of black for formatting.

- CHANGELOG.md
- orthoseg/lib/prepare_traindatasets.py
- orthoseg/util/ows_util.py
- tests/test_prepare_traindata.py
- refactor test_prepare_traindata
- added test to reuse image or not
resolves https://github.com/orthoseg/orthoseg/issues/170
> ENH: In prepare_trainingdata, reuse images already available in previous version

- CHANGELOG.md
- orthoseg/helpers/config_helper.py
- orthoseg/lib/prepare_traindatasets.py
- orthoseg/predict.py
- tests/test_config.py
- improvements to logging
- add `image_layer` to email subject for `predict`: closes #173
> ENH: add image_layer to email subject for predict + other small improvements

- orthoseg/helpers/config_helper.py
- orthoseg/load_images.py
- orthoseg/postprocess.py
- orthoseg/predict.py
- orthoseg/train.py
- orthoseg/validate.py
- Wasn't robust when in some cases, like if multiple runs were ran in the same process
- Some code cleanup
> ENH: improve handling of run and general tmp dir

- orthoseg/util/ows_util.py
Ignore an extra error somethimes thrown by rasterio that doesn't seem relevant
> ENH: make loading images more robust

- CHANGELOG.md
- orthoseg/lib/postprocess_predictions.py
- orthoseg/load_images.py
- orthoseg/postprocess.py
- orthoseg/predict.py
- orthoseg/train.py
- orthoseg/validate.py
- tests/test_load_images.py
- tests/test_postprocess.py
- tests/test_predict.py
- tests/test_train.py
- tests/test_validate.py
> ENH: improve messages in emails being sent

- orthoseg/lib/predicter.py
- orthoseg/predict.py
- sample_projects/imagelayers.ini
- tests/test_end2end.py
- tests/test_predict.py
Doesn't need to be added to changelog as it was never released: bug introduced in #228
Test added to avoid regression.
> BUG: fix done files not being skipped introduced in #228

- orthoseg/lib/predicter.py
- orthoseg/predict.py
- fix email message containing layer config instead of name
- Bug introduced without being released, so not in changelog...
- minor refactor in predict
> BUG: fix email message containing layer config instead of name

- orthoseg/__init__.py
- orthoseg/helpers/config_helper.py
- orthoseg/lib/cleanup.py
- orthoseg/lib/predicter.py
- orthoseg/lib/trainer.py
- orthoseg/model/model_helper.py
- orthoseg/train.py
- orthoseg/util/git_downloader.py
- orthoseg/util/log_util.py
- pyproject.toml
- setup.py
- tests/test_postprocess_predictions.py
- tests/test_predict.py
Enable flake8-pathlib ruleset for ruff + fix errors
> MAINT: enable flake8-pathlib ruleset for ruff
